services:
  - type: web
    name: bdesh-ecom-web
    env: docker
    plan: free
    healthCheckPath: /api/health
    buildCommand: "npm run build"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PURBOPACK
        value: "0"
      - key: NEXT_PUBLIC_APP_URL
        value: https://bdesh-ecom-web.onrender.com
      - key: NEXT_PUBLIC_BASE_URL
        value: https://bdesh-ecom-web.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NEXTAUTH_SECRET
        value: 3805138e506e790c6bc3747e4b7bdf7caf7d5743304afffd6996ca807dafba88
      - key: NEXTAUTH_URL
        value: https://bdesh-ecom-web.onrender.com
      - key: DATABASE_URL
        value: postgresql://postgres:ashxyz187@localhost:5433/bdesh_ecom

databases:
  - name: bdesh-ecom-db
    databaseName: bdesh_ecom
    plan: free
